# Generated by Django 3.0.4 on 2020-04-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsletter',
        ),
    ]
